apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["gets", "list", "watch"]

    
# check the role is applied or  not
kubectl auth can-i watch pods --as=default -n default
# Edit the runing role and apply on same time
 kubectl edit role pod-reader